
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-happy-cows-w24-4pm-1
owner: ucsb-cs156-w24
repo_name: proj-happy-cows-w24-4pm-1
pull_requests: [{"author":{"id":"U_kgDOBXzOFw","is_bot":false,"login":"jinanthony","name":""},"headRefName":"AJ--B1Backend","number":30,"title":"AJ -- B1 Backend","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-1/pull/30"},{"author":{"id":"MDQ6VXNlcjkxMjg3MTQw","is_bot":false,"login":"jtanggy","name":"Likhit Gudisay"},"headRefName":"Announce-f1","number":28,"title":"Epic: Add Announcements - B1, B2, F1    (DONT MERGE, WILL BE SPLIT UP INTO ORIGINAL PRS)","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-1/pull/28"},{"author":{"id":"MDQ6VXNlcjkxMjg3MTQw","is_bot":false,"login":"jtanggy","name":"Likhit Gudisay"},"headRefName":"LG-buycow","number":22,"title":"Lg buycow","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-1/pull/22"}]
