
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-happy-cows-w24-4pm-1
owner: ucsb-cs156-w24
repo_name: proj-happy-cows-w24-4pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjgzODAwODc1","is_bot":false,"login":"TianyiYang-Tyler","name":""},"headRefName":"Add-backend-endpoints","number":37,"title":"showChat controller impl with tests - T. Yang","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-1/pull/37"},{"author":{"id":"U_kgDOCU6okQ","is_bot":false,"login":"chrisriney4","name":""},"headRefName":"Chris-Announce","number":36,"title":"B2: Swagger Endpoints (Post, Get, Put, Delete), Epic: Add Announcements ","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-1/pull/36"}]
