
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-happy-cows-w24-4pm-1
owner: ucsb-cs156-w24
repo_name: proj-happy-cows-w24-4pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjkxMjg3MTQw","is_bot":false,"login":"jtanggy","name":"Likhit Gudisay"},"headRefName":"AnnounceDev","number":24,"title":"B1 (Entity and Repo files), Epic: Add announcements","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-1/pull/24"},{"author":{"id":"MDQ6VXNlcjkxMjg3MTQw","is_bot":false,"login":"jtanggy","name":"Likhit Gudisay"},"headRefName":"LG-buycow","number":22,"title":"Lg buycow","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-1/pull/22"},{"author":{"id":"MDQ6VXNlcjkxMjg3MTQw","is_bot":false,"login":"jtanggy","name":"Likhit Gudisay"},"headRefName":"LG-negcow","number":21,"title":"fix bug negative cows sold","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-1/pull/21"},{"author":{"id":"MDQ6VXNlcjkxMjg3MTQw","is_bot":false,"login":"jtanggy","name":"Likhit Gudisay"},"headRefName":"LG-whitespace","number":20,"title":"Added whitespace","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-1/pull/20"},{"author":{"id":"MDQ6VXNlcjkxMjg3MTQw","is_bot":false,"login":"jtanggy","name":"Likhit Gudisay"},"headRefName":"LG-pagination","number":19,"title":"added pagination to OurTable - LG","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-1/pull/19"},{"author":{"id":"U_kgDOBdHZtA","is_bot":false,"login":"alexanderthomasucsb","name":""},"headRefName":"addAnnouncementTableAndForm","number":18,"title":"Add announcement table and form","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-1/pull/18"},{"author":{"id":"U_kgDOBXzOFw","is_bot":false,"login":"jinanthony","name":""},"headRefName":"AJ----fix-typo-in-gamePlay.md","number":1,"title":"AJ -- fix typo in gamePlay.md","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-1/pull/1"}]
